// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.1
// source: lobby.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGuestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Uid  int32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetGuestReq) Reset() {
	*x = GetGuestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestReq) ProtoMessage() {}

func (x *GetGuestReq) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestReq.ProtoReflect.Descriptor instead.
func (*GetGuestReq) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *GetGuestReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetGuestReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetGuestRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Uid      string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	NickName string `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadIcon int32  `protobuf:"varint,5,opt,name=headIcon,proto3" json:"headIcon,omitempty"`
	GameCoin int32  `protobuf:"varint,6,opt,name=gameCoin,proto3" json:"gameCoin,omitempty"`
	Strength int32  `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Rank     int32  `protobuf:"varint,8,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *GetGuestRes) Reset() {
	*x = GetGuestRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestRes) ProtoMessage() {}

func (x *GetGuestRes) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestRes.ProtoReflect.Descriptor instead.
func (*GetGuestRes) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *GetGuestRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetGuestRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetGuestRes) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetGuestRes) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *GetGuestRes) GetHeadIcon() int32 {
	if x != nil {
		return x.HeadIcon
	}
	return 0
}

func (x *GetGuestRes) GetGameCoin() int32 {
	if x != nil {
		return x.GameCoin
	}
	return 0
}

func (x *GetGuestRes) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *GetGuestRes) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type UpdateGameCoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameCoin int32  `protobuf:"varint,2,opt,name=gameCoin,proto3" json:"gameCoin,omitempty"`
	Operate  string `protobuf:"bytes,3,opt,name=operate,proto3" json:"operate,omitempty"`
	Type     int32  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *UpdateGameCoinReq) Reset() {
	*x = UpdateGameCoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameCoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameCoinReq) ProtoMessage() {}

func (x *UpdateGameCoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameCoinReq.ProtoReflect.Descriptor instead.
func (*UpdateGameCoinReq) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateGameCoinReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateGameCoinReq) GetGameCoin() int32 {
	if x != nil {
		return x.GameCoin
	}
	return 0
}

func (x *UpdateGameCoinReq) GetOperate() string {
	if x != nil {
		return x.Operate
	}
	return ""
}

func (x *UpdateGameCoinReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type UpdateGameCoinRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CoinBalance int32  `protobuf:"varint,2,opt,name=coinBalance,proto3" json:"coinBalance,omitempty"`
	Code        string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UpdateGameCoinRes) Reset() {
	*x = UpdateGameCoinRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameCoinRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameCoinRes) ProtoMessage() {}

func (x *UpdateGameCoinRes) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameCoinRes.ProtoReflect.Descriptor instead.
func (*UpdateGameCoinRes) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGameCoinRes) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateGameCoinRes) GetCoinBalance() int32 {
	if x != nil {
		return x.CoinBalance
	}
	return 0
}

func (x *UpdateGameCoinRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateEmbattleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TeamId     int32  `protobuf:"varint,2,opt,name=teamId,proto3" json:"teamId,omitempty"`
	MonsterId  int32  `protobuf:"varint,4,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	SequenceId int32  `protobuf:"varint,5,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
	Code       string `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UpdateEmbattleReq) Reset() {
	*x = UpdateEmbattleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEmbattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmbattleReq) ProtoMessage() {}

func (x *UpdateEmbattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmbattleReq.ProtoReflect.Descriptor instead.
func (*UpdateEmbattleReq) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEmbattleReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateEmbattleReq) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *UpdateEmbattleReq) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *UpdateEmbattleReq) GetSequenceId() int32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *UpdateEmbattleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdatePropReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ItemName string `protobuf:"bytes,2,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Operate  string `protobuf:"bytes,3,opt,name=operate,proto3" json:"operate,omitempty"`
	Amount   int32  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Code     string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UpdatePropReq) Reset() {
	*x = UpdatePropReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropReq) ProtoMessage() {}

func (x *UpdatePropReq) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropReq.ProtoReflect.Descriptor instead.
func (*UpdatePropReq) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePropReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdatePropReq) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *UpdatePropReq) GetOperate() string {
	if x != nil {
		return x.Operate
	}
	return ""
}

func (x *UpdatePropReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdatePropReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateEquipmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EquipmentUId int32  `protobuf:"varint,2,opt,name=equipmentUId,proto3" json:"equipmentUId,omitempty"`
	EquipmentId  int32  `protobuf:"varint,3,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`
	MonsterId    int32  `protobuf:"varint,4,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Code         string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UpdateEquipmentReq) Reset() {
	*x = UpdateEquipmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEquipmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEquipmentReq) ProtoMessage() {}

func (x *UpdateEquipmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEquipmentReq.ProtoReflect.Descriptor instead.
func (*UpdateEquipmentReq) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEquipmentReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateEquipmentReq) GetEquipmentUId() int32 {
	if x != nil {
		return x.EquipmentUId
	}
	return 0
}

func (x *UpdateEquipmentReq) GetEquipmentId() int32 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

func (x *UpdateEquipmentReq) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *UpdateEquipmentReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateMonsterExperienceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MonsterUId   int32  `protobuf:"varint,2,opt,name=monsterUId,proto3" json:"monsterUId,omitempty"`
	MonsterLevel int32  `protobuf:"varint,3,opt,name=monsterLevel,proto3" json:"monsterLevel,omitempty"`
	MonsterExp   int32  `protobuf:"varint,4,opt,name=monsterExp,proto3" json:"monsterExp,omitempty"`
	Code         string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UpdateMonsterExperienceReq) Reset() {
	*x = UpdateMonsterExperienceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMonsterExperienceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonsterExperienceReq) ProtoMessage() {}

func (x *UpdateMonsterExperienceReq) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonsterExperienceReq.ProtoReflect.Descriptor instead.
func (*UpdateMonsterExperienceReq) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMonsterExperienceReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateMonsterExperienceReq) GetMonsterUId() int32 {
	if x != nil {
		return x.MonsterUId
	}
	return 0
}

func (x *UpdateMonsterExperienceReq) GetMonsterLevel() int32 {
	if x != nil {
		return x.MonsterLevel
	}
	return 0
}

func (x *UpdateMonsterExperienceReq) GetMonsterExp() int32 {
	if x != nil {
		return x.MonsterExp
	}
	return 0
}

func (x *UpdateMonsterExperienceReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_lobby_proto protoreflect.FileDescriptor

var file_lobby_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x33, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0xcd, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x49,
	0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x65, 0x61, 0x64, 0x49,
	0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x6e, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22,
	0x6f, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x5b, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x69, 0x6e, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f,
	0x69, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x8f, 0x01,
	0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x83, 0x01, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x55,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x1a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x72, 0x55, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x6f, 0x6e,
	0x73, 0x74, 0x65, 0x72, 0x55, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData = file_lobby_proto_rawDesc
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_proto_rawDescData)
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lobby_proto_goTypes = []interface{}{
	(*GetGuestReq)(nil),                // 0: proto.lobby.GetGuestReq
	(*GetGuestRes)(nil),                // 1: proto.lobby.GetGuestRes
	(*UpdateGameCoinReq)(nil),          // 2: proto.lobby.updateGameCoinReq
	(*UpdateGameCoinRes)(nil),          // 3: proto.lobby.updateGameCoinRes
	(*UpdateEmbattleReq)(nil),          // 4: proto.lobby.updateEmbattleReq
	(*UpdatePropReq)(nil),              // 5: proto.lobby.updatePropReq
	(*UpdateEquipmentReq)(nil),         // 6: proto.lobby.updateEquipmentReq
	(*UpdateMonsterExperienceReq)(nil), // 7: proto.lobby.updateMonsterExperienceReq
}
var file_lobby_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuestRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameCoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameCoinRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEmbattleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePropReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEquipmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMonsterExperienceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_rawDesc = nil
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
